# -*- coding: utf-8 -*-
"""DEYOUNG COMMUNICATION Project Dossier - content part A (chapters 1-7).

Block kinds: p, h2, h3, bullets, table, callout, image, note
"""

CH_A = [
{
 "num": 1, "title": "Executive Summary and Brand Direction",
 "blocks": [
  ("p", "DEYOUNG COMMUNICATION is an AI communications platform that lets individuals, businesses, and agencies hire AI employees: voice and text agents that answer calls, hold natural conversations, execute approved tools, remember customers, and hand conversations to humans when the situation calls for it. This dossier is the Phase 1 planning package produced before implementation. It consolidates twenty-four required deliverables, from market research and competitor analysis through the product requirements document, technical specification, system and worker architecture, voice architecture, database schema, API design, permission and consent models, UX sitemap, screen inventory, design system, 3D and motion proposal, deployment and cost strategy, risk register, and implementation roadmap. Every decision in this document is written to survive contact with real engineering: no capability is claimed unless a production-grade path exists for it, and no number is presented unless it comes from a cited public source or an explicit engineering budget."),
  ("h2", "Brand Name Decision"),
  ("p", "The working name DEYOUNGCOMMUNICATION was evaluated against five public-facing variants: DEYOUNG COMMUNICATION, DEYOUNG COMM, DEYOUNG CONNECT, DEYOUNG VOICE, and DEYOUNG COMMUNICATIONS. The recommended public-facing brand is DEYOUNG COMMUNICATION, set as two words with a wordmark lockup. The reasoning is documented below rather than decided casually, as the master brief requires."),
  ("table", {
    "caption": "Table 1.1: Brand name option evaluation",
    "ratios": [0.24, 0.46, 0.30],
    "headers": ["Candidate", "Assessment", "Verdict"],
    "rows": [
      ["DEYOUNG COMMUNICATION", "Reads as a company about the act of communicating, which matches the product philosophy of selling communication rather than AI. Clean possessive-free construction, strong wordmark rhythm, and natural domain variants (deyoungcommunication.com, deyoungcomm.com).", "Selected"],
      ["DEYOUNG COMMUNICATIONS", "The plural is the telecom-industry default, so it reads as infrastructure-first and blends in with thousands of legacy telcos and PBX vendors. It also invites the DEYOUNG COMM abbreviation, which weakens the brand.", "Rejected"],
      ["DEYOUNG CONNECT", "Short and app-like, but generic. Dozens of connectivity products already use Connect and it discards the equity of the full family name.", "Rejected"],
      ["DEYOUNG VOICE", "Accurately names the flagship capability, but it anchors the company to voice only and conflicts with the planned multi-channel roadmap (chat, SMS, email, WhatsApp).", "Rejected"],
      ["DEYOUNG COMM", "Functional as a short social handle and favicon-safe compact mark, but not strong enough to lead. Adopted as the secondary compact wordmark only.", "Secondary mark"],
    ],
  }),
  ("p", "The brand personality must communicate communication, intelligence, trust, speed, human-like interaction, professional service, and modern infrastructure. In practice this translates to a voice that is precise rather than hype-driven, an interface that shows real system state rather than decorative activity, and a visual identity built on the disciplined use of red, white, and black. The brand never claims sentience, never fabricates social proof, and never dresses a roadmap item as a shipped feature. This restraint is itself a positioning weapon in a market where most AI landing pages are interchangeable gradients and invented metrics."),
  ("h2", "Non-Negotiable Product Principles"),
  ("bullets", [
   "Honesty first: fake customers, fake reviews, fake call statistics, fake integrations, and fake system activity are forbidden. If a capability is not implemented, the UI labels it as unavailable, coming soon, or configuration required.",
   "The product sells communication, not AI: the user should feel they hired an employee, the caller should feel they are talking to someone who understands them, and the owner should see exactly what their AI employee is doing.",
   "Voice quality is a product feature: the AI must sound conversational, handle interruptions naturally, and stay silent when nothing real is happening. No beeps, no fake waiting sounds, no robotic filler.",
   "Consent is architectural: voice cloning, recording, transcription, and data retention all require explicit, revocable, auditable consent designed into the schema rather than bolted on.",
   "Free-first economics: the architecture must reach a first paying customer without sunk infrastructure cost, while never sacrificing security or reliability to claim something is free.",
  ]),
  ("h2", "Deliverable Index"),
  ("p", "The master brief demands twenty-four deliverables before implementation. They are distributed across this dossier as follows: research report and competitor analysis in Chapter 2; product requirements in Chapter 3; technical specification in Chapter 4; system and worker architecture in Chapter 5; voice architecture in Chapter 6; database schema and API architecture in Chapter 7; permission, security, and consent models in Chapter 8; UX sitemap and screen inventory in Chapter 9; design system, brand identity proposal, and logo direction in Chapter 10; the 3D and motion system proposal in Chapter 11; responsive strategy and deployment architecture in Chapter 12; cost analysis and free-first strategy in Chapter 13; and the risk register and implementation roadmap in Chapter 14. Phase 2, which follows this dossier, implements the marketing website and the web application against these specifications."),
 ],
},
{
 "num": 2, "title": "Market Research and Competitor Analysis",
 "blocks": [
  ("h2", "Market Context"),
  ("p", "Voice AI agents crossed from demo to deployment between 2023 and 2025 as three component costs collapsed simultaneously: streaming speech-to-text fell to well under one cent per minute, streaming text-to-speech reached conversational quality at scale, and large language model inference became fast enough to sustain sub-second conversational turn-taking. Public coverage of the category in 2025 and 2026 describes a maturing market where buyers no longer ask whether AI can hold a phone conversation, but instead compare latency, interruption handling, telephony coverage, compliance posture, and price per minute. That shift matters for a new entrant: the differentiation battle has moved from existence of the technology to the quality of the employee experience around it, which is exactly where DEYOUNG COMMUNICATION's hiring metaphor, control room, and consent architecture are aimed."),
  ("p", "At the same time, the category's pricing is publicly transparent in a way most software categories are not. Several competitors publish per-minute ranges, which allows a precise cost position to be chosen rather than guessed. The research below draws on public pricing pages, published plan structures, and community comparisons as of late 2025 through 2026, and every figure used in this dossier is labeled with its public source character so the numbers can be re-verified before any go-to-market claim is made. No private or scraped data is used, and no figure is invented."),
  ("h2", "Competitor Profiles"),
  ("table", {
    "caption": "Table 2.1: Direct competitor profile summary (public information, 2025-2026)",
    "ratios": [0.16, 0.30, 0.26, 0.28],
    "headers": ["Platform", "Positioning and strengths", "Public pricing signal", "Gaps DEYOUNG can attack"],
    "rows": [
      ["Bland AI", "Enterprise-focused voice agent API. Strong telephony spine, pathways feature for routing, established brand with agencies.", "Roughly $0.11-0.14 per minute in tiered plans; published base fees on Build tiers around $299 per month; telephony billed separately.", "High minimum spend prices out individuals and small businesses. Hiring metaphor and human handoff tooling are thin."],
      ["Retell AI", "Popular with startups building on top of it. Flexible LLM/TTS/telephony choices, good conversation quality tuning.", "Commonly reported all-in ranges around $0.07-0.31 per minute depending on chosen components; starter plans around $29.", "Costs swing widely with component choice. Buyer assembles their own employee experience; little unified control room."],
      ["Vapi", "Developer-first orchestration, bring-your-own-provider model with speech, LLM, and voice billed at cost.", "Platform portion around $0.05 per minute plus provider costs at cost, per public plan pages and user reports.", "Developer-centric: no turnkey hiring flow for non-technical business owners, limited customer memory and consent tooling."],
      ["Synthflow", "No-code agent builder aimed at non-technical users, template library, strong funnel marketing.", "Plan-based tiers reported from roughly $29 to $99+ with per-minute rates in the $0.08-0.09 area on higher tiers.", "Conversational depth and control-room transparency are limited; geared to volume outbound more than durable inbound employees."],
      ["Tel-Agent", "Open-source (AGPL-3.0) LiveKit-based voice agent starter. Full pipeline reference including SIP bridge and agent worker.", "No platform fee when self-hosted; operators pay providers and infrastructure directly.", "Self-hosting burden, no multi-tenant product layer, AGPL obligations make direct code reuse unattractive commercially."],
    ],
  }),
  ("image", {"path": "scripts/competitor_pricing.png", "caption": "Figure 2.1: Public per-minute platform price ranges, 2025-2026. Ranges summarize public plan pages and independent comparisons; verify before external use."}),
  ("p", "The pricing picture yields a clear strategic conclusion. The hosted platforms monetize a platform margin on top of raw provider costs, and the open-source option shifts all integration and operations burden to the operator. DEYOUNG COMMUNICATION's free-first, bring-your-own-key tier can sit structurally below every hosted competitor for cost-sensitive users while the managed tier remains competitive at small-business scale, because the platform margin is decoupled from provider spend. This is only honest if the BYO tier is real: keys must be encryptable per organization, metered, and never exposed to the client, which is specified in Chapter 8."),
  ("h2", "Tel-Agent Assessment and License Analysis"),
  ("p", "Tel-Agent is an open-source project (repository github.com/Dpro-at, AGPL-3.0) that demonstrates a complete LiveKit-based voice agent pipeline: a media bridge from SIP/WebRTC into LiveKit rooms, a Python agent worker consuming the audio stream, and pluggable speech and model providers. Its value to this project is architectural confirmation that the LiveKit agent pattern works end-to-end for telephony. Its code is deliberately not being copied."),
  ("table", {
    "caption": "Table 2.2: AGPL-3.0 implications for DEYOUNG COMMUNICATION",
    "ratios": [0.28, 0.72],
    "headers": ["Scenario", "Consequence"],
    "rows": [
      ["Copy Tel-Agent server code into the platform", "AGPL is strong network copyleft: offering the platform over a network triggers source-disclosure obligations for the entire derivative work, including proprietary orchestration and billing code. Not acceptable for a commercial SaaS.", ],
      ["Run Tel-Agent unmodified as an isolated self-hosted component", "Still AGPL for that component. Users interacting with it over the network would be entitled to its source (which they have), but coupling it tightly with proprietary code risks derivative-work arguments. Operationally doubles the deployment surface.", ],
      ["Study architecture, reimplement independently", "Clean-room reimplementation of documented, public concepts (rooms, tracks, agent workers) carries no AGPL obligation because copyright protects expression, not ideas. This is the chosen path.", ],
      ["Commercial licensing", "If deep reuse ever becomes valuable, the project maintainer could be approached for a commercial license. Not required under the independent-implementation strategy.", ],
    ],
  }),
  ("h2", "Nigeria and Emerging-Market Context"),
  ("p", "The master brief calls out Nigeria accessibility as an evaluation dimension, so the research treats it as a first-class constraint rather than a footnote. Three facts shape the plan. First, WhatsApp is the dominant business messaging channel in Nigeria, and Meta has announced per-message charges for businesses on the WhatsApp Business Platform in Nigeria taking effect October 1, 2026, which means WhatsApp economics must be modeled per conversation and disclosed to users rather than advertised as free. Second, bulk SMS remains cheap and fast, which keeps SMS a viable, low-cost channel and a practical fallback where data connectivity is intermittent. Third, local infrastructure investment, including operator AI data-center expansion, is improving hosting options, though the default architecture still assumes regions outside Nigeria and optimizes for latency to African network operators where provider presence allows."),
  ("p", "Practical consequences for the platform: pricing tiers must support naira-friendly entry points and usage-based billing rather than large fixed seats; SMS and WhatsApp channels carry country-specific cost tables surfaced honestly in the UI; and the free-first strategy in Chapter 13 deliberately uses services with generous free tiers so a Lagos agency can bring its first client onto the platform at near-zero fixed cost. Payment-provider selection is left as a configuration decision documented in the integration matrix, because local payment rails change faster than the platform should ship hard-coded opinions about them."),
 ],
},
{
 "num": 3, "title": "Product Requirements Document",
 "blocks": [
  ("h2", "Users and Accounts"),
  ("p", "The platform supports three account types that share one codebase and one permission model. Individual users create a single personal workspace with one or more AI assistants, useful for solo professionals such as consultants, creators, and independent service providers who miss calls while working. Business accounts create an organization with one or many AI employees, shared team inbox, customer memory, and role-based access for staff. Agency accounts manage multiple client organizations under one parent account, with cross-organization reporting, white-label touches, and per-client billing separation. The agency type is the highest-value segment because it multiplies seat-based usage across client organizations, and its needs (isolation, audit, delegated administration) drive several schema decisions in Chapter 7."),
  ("h2", "AI Employee Capabilities"),
  ("p", "An AI employee is a first-class entity the user configures as they would onboard a staff member. The builder captures name, role, purpose, personality, tone, speaking style, business instructions, conversation rules, escalation rules, knowledge sources, tool permissions, channels, working hours, human handoff rules, voice, language, security permissions, and memory behavior. Role templates (AI Receptionist, Sales Assistant, Customer Support Agent, Appointment Scheduler, Virtual Assistant, Front Desk Agent, Lead Qualification Agent, Business Information Agent, Personal Assistant) pre-fill sensible defaults but every field remains editable, because the builder must feel like configuring a real employee rather than filling a toy chatbot form."),
  ("table", {
    "caption": "Table 3.1: Capability matrix by delivery phase",
    "ratios": [0.30, 0.24, 0.23, 0.23],
    "headers": ["Capability", "Phase 0 (foundation)", "Phase 1 (core product)", "Phase 2 (scale)"],
    "rows": [
      ["AI employee builder", "Full schema, UI with all fields, honest validation", "Templates library, voice preview", "Multi-language employees"],
      ["Phone channel", "UI shows Not connected until telephony configured", "SIP trunk + number provisioning, inbound and authorized outbound", "Regional number catalogs, carrier failover"],
      ["Web chat", "Embeddable widget with real transcript", "Proactive triggers, visitor context", "Co-browsing hooks (integration required)"],
      ["SMS and WhatsApp", "Channel pages with connection states", "Two-way messaging with templates and opt-in capture", "Campaign automation flows"],
      ["Live call control room", "Empty state and read-only room", "Live transcript, waveform, AI action display, takeover, transfer, notes", "Barge-in coaching, whisper to AI"],
      ["Knowledge system", "Upload with honest processing states", "Chunking, embeddings, retrieval with citations", "Versioning, refresh, CRM sync"],
      ["Automations", "Schema and canvas placeholder", "Trigger, condition, AI action, tool action, routing, log", "3D node-graph view, marketplace"],
      ["Voice studio", "Voice catalog with samples", "Voice signature visualization, speed and prosody tuning", "Consent-based cloning with revocation"],
      ["Analytics", "No data, honest empty states", "Per-employee and per-channel metrics from real usage events", "Cohort and outcome analytics"],
    ],
  }),
  ("p", "The phasing rule is that every phase ships interfaces that are real where implemented and honestly labeled where not. A channel page that has never been configured reads Not connected with the exact steps required; a dashboard with zero calls reads No calls yet and offers the action that creates the first call; an automation canvas exists only once its execution engine exists, never as a decorative mockup. This is the single most brand-defining product decision in the document, and Chapter 9's screen inventory encodes it as a required empty state per screen."),
  ("h2", "Human Handoff"),
  ("p", "Handoff is modeled as an explicit state machine: AI handling, human requested, transfer pending, human connected, human handling, returned to AI, and call ended. The control room surfaces the current state, who requested the handoff, and why. When a human takes over, the AI stops speaking immediately, the transcript continues in a shared timeline with speaker attribution, and the AI remains context-loaded so the conversation can return to it without information loss. Escalation rules on the employee decide when the AI requests a human on its own, including confidence triggers, sentiment triggers, and keyword triggers; every escalation is logged with its reason so owners can tune rules from evidence rather than vibes."),
  ("h2", "Mobile Application"),
  ("p", "Native mobile is planned as a companion, not a shrunken dashboard: Home, Calls, AI, Inbox, and More tabs oriented around monitoring and takeover on the go. App Store and Google Play entries remain honestly labeled Coming soon with a real waitlist mechanism until builds ship; download links are never faked. Mobile-specific interaction patterns (call takeover as a native call screen, push alerts for escalations, swipe actions on inbox items) are specified so the mobile app is designed, not squeezed. Performance rules from Chapter 11 apply with stricter budgets on mobile, and every 3D element falls back to its CSS tier on low-end devices."),
 ],
},
{
 "num": 4, "title": "Technical Specification",
 "blocks": [
  ("h2", "Stack Selection"),
  ("p", "The stack was selected against eight explicit criteria from the master brief: cost, latency, reliability, developer experience, Nigeria accessibility, free-tier availability, scalability, and vendor lock-in, plus privacy and licensing as gating constraints. The chosen stack keeps every component either open-source or available with a meaningful free tier, and it avoids any provider whose free tier cannot carry a first customer."),
  ("table", {
    "caption": "Table 4.1: Stack decisions and rationale",
    "ratios": [0.22, 0.26, 0.52],
    "headers": ["Layer", "Choice", "Rationale"],
    "rows": [
      ["Frontend", "Next.js (App Router) + TypeScript + Tailwind CSS + shadcn/ui", "One framework covers marketing site, web app, and embeddable chat widget with code-splitting for 3D bundles. TypeScript is non-negotiable for a product with this much state. shadcn/ui gives accessible primitives that are owned, not rented."],
      ["API layer", "Next.js route handlers (REST) + WebSocket service for realtime", "Colocated REST keeps Phase 0 deployment simple and reviewable. Realtime transcript and call events use a dedicated WebSocket/SSE service so page interactions never compete with call streams."],
      ["Database", "PostgreSQL (Neon or self-hosted) + Prisma ORM", "Relational integrity for organizations, consent, and audit is a compliance requirement, not a preference. Row-level scoping enforced at the query layer. Prisma migrations are reviewable SQL."],
      ["Cache and queues", "Redis (Upstash) for cache and streams", "Free tier carries the first customers; streams power worker queues with consumer groups; pub/sub fans out live call events."],
      ["Object storage", "S3-compatible (Cloudflare R2)", "Zero-egress pricing matters for audio recordings and knowledge documents; standard S3 API avoids lock-in."],
      ["Voice media", "LiveKit (open-source) with SIP bridge, Twilio Programmable Voice as alternate ingress", "LiveKit agents pattern is proven by open-source reference projects; SIP bridge terminates real phone calls; Twilio option covers regions where its numbers are easier to provision."],
      ["AI providers", "Deepgram or Whisper for STT; OpenAI or Anthropic for LLM; ElevenLabs or PlayHT for TTS behind a provider abstraction", "Each slot has two candidates behind one interface, so provider pricing or policy changes never require product surgery. BYO keys supported with encrypted storage."],
      ["Auth", "Self-hosted session auth with argon2 password hashing, or Auth.js where a provider is required", "Session cookies keep auth free-tier friendly; RBAC is enforced server-side in every query path; no client-side tokens for privileged operations."],
    ],
  }),
  ("h2", "Provider Abstraction"),
  ("p", "Every external capability (STT, LLM, TTS, telephony, storage, messaging) sits behind an internal interface with at least two implementations. The abstraction defines latency budgets, streaming semantics, error contracts, and cost meters per provider so the orchestrator can route by policy: cheapest, fastest, or pinned by the account owner. Provider credentials live server-side only, encrypted per organization for BYO keys, and are never included in any client bundle. This single design decision is what makes the free-first and BYO strategies honest instead of aspirational."),
  ("h2", "Realtime Transport"),
  ("p", "Voice media flows through LiveKit rooms; call control events, transcript deltas, and AI action notifications flow over a WebSocket gateway backed by Redis pub/sub, so any dashboard session can subscribe to the calls it is permitted to see. Web chat uses SSE for visitor-to-server messages and the same WebSocket for agent-side views. All realtime payloads are typed and versioned, because a live call control room cannot tolerate schema drift between the worker that emits events and the client that renders them."),
 ],
},
{
 "num": 5, "title": "System and Worker Architecture",
 "blocks": [
  ("h2", "Request Lifecycle"),
  ("p", "Every conversation, inbound or outbound, follows one lifecycle: channel ingress (phone call, chat message, SMS, webhook), gateway (media gateway for audio, API gateway for events), the AI orchestrator, which resolves employee configuration, permissions, and context policy; context and memory assembly from organization-scoped stores; worker routing to the specialist workers; external provider calls where required; response streaming back to the channel; and usage events written for metering, audit, and analytics. The orchestrator is deliberately thin: it decides who works, with what permissions, on what data, and when to escalate. It does not itself transform audio or generate text, which keeps the brain auditable and the workers replaceable."),
  ("image", {"path": "scripts/dossier_architecture.png", "caption": "Figure 5.1: Platform architecture overview. Layers connect top to bottom; the orchestrator (red border) is the only component that makes policy decisions."}),
  ("h2", "Worker Topology"),
  ("table", {
    "caption": "Table 5.1: Worker responsibilities and scale policy",
    "ratios": [0.17, 0.45, 0.38],
    "headers": ["Worker", "Responsibilities", "Scale and idle policy"],
    "rows": [
      ["Voice worker", "Owns the live audio session: VAD, turn detection, barge-in, streaming STT and TTS bridging, interruption cuts.", "One per active call; scales with concurrent calls; idles at zero when no calls are live."],
      ["Text worker", "Streams LLM responses for chat, SMS, WhatsApp, and email with per-employee prompt and rules.", "Pool scales with inbound message rate; cold-start budget under two seconds."],
      ["Tool worker", "Executes approved tools (calendar, CRM writes, lookups) in a sandbox with per-tool permission checks and timeouts.", "Queue-driven; hard timeouts per tool; every execution logged with arguments and result."],
      ["Knowledge worker", "Ingests documents (chunk, embed, index) and serves retrieval with citations for answer grounding.", "Ingestion burst-scaled; retrieval path cached; processing states surfaced honestly to the UI."],
      ["Channel worker", "Delivers messages to each connected channel and normalizes inbound events to the internal envelope format.", "Per-channel queues; backpressure surfaced as channel status (Connected, Needs attention)."],
      ["Automation worker", "Evaluates triggers, runs conditions, sequences AI and tool actions, writes run logs.", "Event-driven; retries with exponential backoff; dead-letter queue with admin visibility."],
      ["Memory worker", "Maintains unified customer profiles: merges interactions, extracts preferences, respects retention rules.", "Batch plus event-driven; every write consent-aware and organization-scoped."],
      ["Analytics worker", "Aggregates usage events into per-employee, per-channel, and outcome metrics.", "Scheduled rollups; dashboards read pre-aggregated tables, never raw events in request paths."],
    ],
  }),
  ("h2", "Orchestration Decisions"),
  ("p", "The orchestrator makes five decision classes on every turn: which worker is needed (a pure routing decision), when to start and stop it (idle shutdown is the default, so an organization with no traffic consumes no worker compute), which provider to use (policy-driven by cost, latency, and pinning), what permissions apply (the worker runs with a scoped token that encodes what data it may touch), and when to escalate to a human (escalation rules plus confidence signals). Every decision is written to the audit log with its inputs, because Chapter 8 requires that a compliance officer can reconstruct why any AI action happened. Workers are independently scalable and independently replaceable, which is the property that lets the platform add a channel or swap a provider without touching the brain."),
 ],
},
{
 "num": 6, "title": "Voice Architecture",
 "blocks": [
  ("h2", "Realtime Pipeline"),
  ("p", "The voice pipeline is a streaming chain with no batch steps: phone or WebRTC audio enters the media gateway; voice activity detection segments speech; streaming STT emits partial hypotheses that feed turn detection; the turn boundary triggers context assembly and the LLM with response streaming; TTS begins speaking the first sentences while generation continues; and audio flows back to the caller. Tool execution slots into the chain as an inline step with a natural filler phrase approved in the employee's voice profile, for example acknowledging the wait before checking a calendar, and the tool's real result drives the next spoken sentence. Nothing in the chain is permitted to fake a result or insert synthetic waiting audio."),
  ("table", {
    "caption": "Table 6.1: End-to-end latency budget (target, p70)",
    "ratios": [0.30, 0.22, 0.48],
    "headers": ["Stage", "Budget", "Notes"],
    "rows": [
      ["VAD turn end detection", "80 ms", "Energy plus semantic turn classifier; endpointing tuned per employee pace."],
      ["STT final hypothesis", "200-300 ms", "Streaming STT partials already available; final at turn end."],
      ["Context and memory fetch", "60 ms", "Pre-fetched on call start; Redis-cached customer profile."],
      ["LLM first token", "300-500 ms", "Prompt sized for first-token speed; longer reasoning deferred to later sentences."],
      ["TTS first audio", "120-200 ms", "Streaming synthesis begins at first sentence boundary."],
      ["Total turn response", "760-1140 ms", "Comfortable conversational window; sub-second perceived with early TTS onset."],
    ],
  }),
  ("h2", "Turn-Taking and Interruption"),
  ("p", "Interruption handling is a safety-gated behavior, not a random feature. While the AI speaks, VAD continues listening; caller speech crossing a threshold immediately fades AI audio out within 150 ms, aborts pending TTS, and marks the generation as interrupted so the LLM receives the new utterance with conversational context. The AI may itself interrupt the customer only under gated conditions: urgent correction (the customer states something factually wrong that the business rules flag), clarification that prevents a misunderstanding, or acknowledgement-style backchannels that humans naturally use. Every AI-initiated interruption is logged with its gate classification, because an AI that constantly interrupts is a defect, and the log is how the behavior gets tuned."),
  ("h2", "Naturalness Standards"),
  ("p", "The voice must not sound like an assistant reading a script. Standards applied in tuning and QA: prosody varies with sentence type; pauses follow punctuation and thought boundaries; short acknowledgements are used the way humans use them; speaking speed adapts to the caller's measured rate; hesitation appears only where a human would hesitate, for example before delivering a number that was just looked up. Forbidden by policy: unnecessary beeps, fake hold music, please wait filler while nothing is being checked, confirmation of every sentence, monotone delivery, and dead air while a tool executes. When a tool runs, the employee says something true about it, then reports the real result."),
  ("h2", "Voice Cloning and Consent Gates"),
  ("p", "Voice cloning is optional, permission-gated, and revocable by design. The consent record stores the voice owner, authorization status, consent timestamp, allowed usage scope, voice ID, creation date, revocation state, and full audit history. Cloning cannot be initiated without an explicit consent artifact (recorded attestation or signed document); usage scope limits where the cloned voice may be deployed; and revocation is immediate, removing the voice from all employees and blocking any in-flight synthesis. The schema in Chapter 7 treats consent as data lineage: a voice without a valid consent record is not loadable by the TTS worker, enforced at the query layer rather than by UI convention."),
 ],
},
{
 "num": 7, "title": "Database Schema and API Architecture",
 "blocks": [
  ("h2", "Core Schema"),
  ("p", "The schema is PostgreSQL with organization-scoped rows as the isolation primitive. Every business table carries organization_id, and server-side query helpers refuse unscoped reads, so cross-tenant leakage is a code-review problem with a compile-time ally rather than a hope. The table below lists the core entities; column-level detail lives in the Prisma migration files that Phase 2 generates from this specification."),
  ("table", {
    "caption": "Table 7.1: Core entities",
    "ratios": [0.24, 0.50, 0.26],
    "headers": ["Entity", "Key columns and semantics", "Notable constraints"],
    "rows": [
      ["users, organizations, memberships", "users (id, email, password_hash, status); organizations (id, type, name, settings); memberships (role: owner, admin, operator, viewer)", "Agency parent linking via organizations.parent_id; role checked on every mutation."],
      ["ai_employees", "id, org, name, role, purpose, personality, tone, instructions, rules, escalation, channels, hours, voice_id, language, memory_policy, status", "Versioned config; draft vs deployed states; deletion soft with retention clock."],
      ["conversations, messages", "conversations (id, org, channel, customer, employee, status); messages (id, conversation, direction, content, speaker, metadata)", "Full-text search on transcripts; retention policy enforced by scheduled job."],
      ["calls, transcripts, events", "calls (id, org, direction, from, to, employee, duration, outcome, recording_ref); transcript rows (speaker, text, confidence); call events (state machine transitions)", "Recording gated by consent flags; waveform amplitude series stored for live UI."],
      ["customers", "id, org, name, phone, email, company, tags, preferences, consent_status, merged_into", "Unified profile; dedupe by phone/email; consent flags drive AI access scope."],
      ["knowledge_sources, chunks", "sources (id, org, type: pdf, docx, txt, url, faq, manual; status, version); chunks (id, source, content, embedding, citation)", "Processing states honest: pending, processing, indexed, failed; delete cascades chunks and vectors."],
      ["automations, runs, steps", "automations (id, org, trigger, conditions, actions graph); runs (id, automation, status, log); steps (id, run, type, input, output, error)", "Every run auditable end to end; dead-letter status surfaced in UI."],
      ["voices, voice_consents", "voices (id, org, provider_voice_id, name, gender, language, sample_ref); consents (id, voice, owner, scope, authorized_at, revoked_at, artifact_ref)", "TTS worker loads voices only where an unrevoked consent row exists."],
      ["integrations, credentials", "integrations (id, org, type, status, config); credentials (id, org, type, encrypted_value, key_version, last_rotated)", "Envelope encryption; decrypted only inside the tool worker; never sent to client."],
      ["phone_numbers, channels", "phone_numbers (id, org, number, provider, capabilities, status); channel connections per org with state and last_error", "States: connected, needs_attention, not_connected, coming_soon."],
      ["usage_events, audit_logs", "usage (id, org, kind, units, cost_estimate, refs); audit (id, org, actor, action, target, reason, ip, at)", "Immutable append-only tables; feeds billing, metering, and compliance review."],
      ["feature_flags, waitlist", "flags (key, org scope, enabled); waitlist (id, email, platform, source, created_at)", "Honest gating of coming-soon surfaces; real waitlist storage for mobile apps."],
    ],
  }),
  ("h2", "API Surface"),
  ("table", {
    "caption": "Table 7.2: Primary REST surface (v1)",
    "ratios": [0.30, 0.14, 0.56],
    "headers": ["Resource", "Methods", "Semantics"],
    "rows": [
      ["/api/v1/auth", "POST", "Session login, logout, refresh; rate-limited; argon2 hashing; audit-logged."],
      ["/api/v1/organizations", "GET, POST, PATCH", "Create and manage orgs; agency parent-child linking; settings including data retention defaults."],
      ["/api/v1/ai-employees", "GET, POST, PATCH, DELETE", "CRUD plus deploy and version endpoints; draft/deploy separation; per-field validation."],
      ["/api/v1/conversations, calls", "GET, POST", "List with filters; call control actions (takeover, transfer, end) validated against state machine."],
      ["/api/v1/customers", "GET, POST, PATCH", "Unified profiles; merge endpoint; consent flag updates restricted to admin roles."],
      ["/api/v1/knowledge", "GET, POST, DELETE", "Source upload with processing state; refresh; delete cascades index entries."],
      ["/api/v1/automations", "GET, POST, PATCH, DELETE", "Graph validation on save; run inspection endpoints."],
      ["/api/v1/voices", "GET, POST", "Catalog with samples; cloning initiation gated on consent artifact upload."],
      ["/api/v1/integrations", "GET, POST, DELETE", "Connect flows store encrypted credentials; status endpoints reflect real provider checks."],
      ["/api/v1/usage, audit", "GET", "Metering and audit queries; admin scopes; export formats for compliance."],
      ["/api/v1/webhooks", "POST", "Inbound provider events; signature-verified; replay-protected; normalized to internal events."],
      ["/ws/realtime", "WS", "Typed, versioned events: transcript deltas, AI action state, call state, channel status."],
    ],
  }),
  ("h2", "Events and Webhooks"),
  ("p", "Internally, every meaningful state change emits a typed event onto Redis streams: conversation started, turn completed, tool executed, escalation requested, handoff completed, automation run finished, usage recorded. Workers consume these streams with consumer groups, which gives at-least-once delivery with idempotent handlers. Externally, organizations can register outbound webhooks for a subset of events, with signature verification, retry with backoff, and a delivery log visible in the UI. Outbound webhooks are an integration surface for real businesses, so they behave like production infrastructure: replay protection, per-endpoint secrets, and honest failure states rather than silent drops."),
 ],
},
]
