# -*- coding: utf-8 -*-
"""DEYOUNG COMMUNICATION Project Dossier - content part B (chapters 8-14)."""

CH_B = [
{
 "num": 8, "title": "Permission, Security and Consent Models",
 "blocks": [
  ("h2", "Role-Based Access Control"),
  ("p", "Access control is organization-scoped RBAC with four roles, enforced server-side on every query and mutation. The UI renders what the API permits; nothing is hidden client-side that the server would still accept. Agency accounts add delegated administration: an agency admin can act inside client organizations only through an explicit agency grant, and every such cross-org action is audit-logged with both the acting user and the target organization."),
  ("table", {
    "caption": "Table 8.1: Role permission matrix",
    "ratios": [0.28, 0.18, 0.18, 0.18, 0.18],
    "headers": ["Capability", "Owner", "Admin", "Operator", "Viewer"],
    "rows": [
      ["Manage billing and plan", "Yes", "No", "No", "No"],
      ["Manage roles and membership", "Yes", "Yes", "No", "No"],
      ["Create and deploy AI employees", "Yes", "Yes", "No", "No"],
      ["Edit employee configuration", "Yes", "Yes", "Drafts only", "No"],
      ["Take over live conversations", "Yes", "Yes", "Yes", "No"],
      ["View conversations and transcripts", "Yes", "Yes", "Yes", "Yes"],
      ["Manage knowledge and integrations", "Yes", "Yes", "No", "No"],
      ["Manage voice consents (grant, revoke)", "Yes", "Yes", "No", "No"],
      ["Export audit and usage data", "Yes", "Yes", "No", "No"],
    ],
  }),
  ("h2", "Security Model"),
  ("p", "Security is treated as a product feature with a visible surface, not a checkbox list. The implemented baseline: session authentication with hardened cookies and CSRF tokens on state-changing routes; argon2id password hashing with per-user salts; rate limiting on auth, API, and webhook endpoints; input validation with typed schemas at every boundary; parameterized queries only, via the ORM, with organization scoping in query helpers; encrypted secrets using envelope encryption with per-environment keys, decrypted only inside the worker that needs them; secure file uploads with type and size validation, virus-scan hook, and randomized storage keys; strict CSP with no inline script execution; and dependency scanning in CI. Provider secrets never reach the client bundle, verified by a build-time check that greps the client output for secret variable names."),
  ("bullets", [
   "Organization isolation is enforced in query helpers, so an unscoped read is a code path that cannot compile, not a convention reviewers must remember.",
   "All privileged actions write immutable audit entries: actor, action, target, reason, source IP, timestamp.",
   "Webhook endpoints verify signatures, reject replays using timestamp windows and nonces, and normalize payloads before they touch domain logic.",
   "Rate limits and lockout policies are conservative by default and tunable per organization by owners.",
   "Secrets rotation is a first-class operation with key versions, so rotation does not require credential re-entry by every user.",
  ]),
  ("h2", "Consent Model"),
  ("p", "Consent is modeled as typed, revocable artifacts rather than a checkbox bit. The platform tracks recording consent (per call, per channel, per jurisdiction notice), transcription consent, data retention consent, voice cloning consent, and channel opt-in state (SMS and WhatsApp opt-ins with timestamps and source). Each artifact records who consented, in what form (verbal attestation captured in the transcript, written acceptance, digital signature), when, for what scope, and its current revocation state. Revocation effects are immediate and mechanical: a revoked recording consent deletes stored audio and keeps only the transcript if separately consented; a revoked cloning consent blocks the TTS worker from loading that voice; a channel opt-out stops all outbound messaging through that channel. AI disclosure requirements are configurable per employee and per jurisdiction, so the platform can honestly say an AI is speaking where the law or the business requires it."),
  ("h2", "Privacy and Retention"),
  ("p", "Privacy pages and controls are generated from the same rules the engine enforces, so documentation cannot drift from behavior. Retention defaults are conservative, per-data-class, and owner-adjustable within policy ceilings; deletion requests execute across relational rows, object storage, vector indexes, and analytics rollups in one auditable job with a completion receipt. Export gives users their data in documented formats. Human access to recordings and transcripts is itself logged, because insider access is part of the privacy surface an enterprise buyer audits. Third-party provider disclosure lists every sub-processor by function with data classes shared, kept current in the integration registry rather than hand-maintained on a marketing page."),
 ],
},
{
 "num": 9, "title": "UX Sitemap and Screen Inventory",
 "blocks": [
  ("h2", "Marketing Sitemap"),
  ("table", {
    "caption": "Table 9.1: Public website structure",
    "ratios": [0.30, 0.70],
    "headers": ["Group", "Routes"],
    "rows": [
      ["Core", "/ (homepage with hero product treatment), /product, /voice-studio, /developers, /pricing, /security, /about, /contact"],
      ["Product pages", "/product/ai-employees, /product/voice, /product/conversations, /product/channels, /product/knowledge, /product/automations, /product/integrations"],
      ["Solutions", "/solutions, /solutions/individuals, /solutions/business, /solutions/agencies"],
      ["Resources", "/resources, /resources/guides, /resources/documentation, /resources/changelog"],
      ["Account", "/login, /signup"],
      ["Legal", "/privacy, /terms, /cookies, /acceptable-use, /voice-consent, /data-retention"],
    ],
  }),
  ("h2", "Application Navigation"),
  ("p", "The app sidebar carries eleven sections: Overview, AI Employees, Live Calls, Inbox, Customers, Knowledge, Voice Studio, Automations, Integrations, Analytics, Settings. Each section has a purpose stated in one line so the IA stays legible as features grow: Overview is the honest state of the account; AI Employees is hiring and configuration; Live Calls is monitoring and control; Inbox is every conversation across channels; Customers is memory; Knowledge is what the AI is allowed to know; Voice Studio is how it sounds; Automations is what it does on its own; Integrations is what it is connected to; Analytics is what actually happened; Settings is who can do what."),
  ("h2", "Screen Inventory with Required Empty States"),
  ("table", {
    "caption": "Table 9.2: App screen inventory (selected core screens)",
    "ratios": [0.26, 0.42, 0.32],
    "headers": ["Screen", "Primary content", "Required honest empty state"],
    "rows": [
      ["Overview dashboard", "Account status cards: employees, live calls, conversations, channel health, usage.", "New account: Create your first AI employee, Connect an integration, No calls yet. Zero invented metrics."],
      ["AI Employees list", "Cards with name, role, status, channels, last activity.", "No employees: Create your first AI employee with role templates."],
      ["Employee builder", "Sections for identity, instructions, knowledge, tools, channels, voice, permissions.", "Fields validate honestly; unavailable capabilities render labeled Coming soon or Configuration required, never disabled-fake."],
      ["Live Calls room", "Active call cards; detail view with transcript, waveform, AI action, controls.", "No live calls: No live calls right now, with link to test call (only if telephony configured; otherwise states Not connected)."],
      ["Inbox", "Conversation threads across channels with assignment and status.", "No conversations: Nothing here yet. Connect a channel to start receiving conversations."],
      ["Customers", "Profile cards with history, notes, tags, consent status.", "No customers: Customers appear here after your first conversations."],
      ["Knowledge", "Source table with type, status, version, last updated.", "No sources: Add your first knowledge source (PDF, DOCX, TXT, URL, FAQ, or manual entry)."],
      ["Voice Studio", "Voice catalog with samples, tuning controls, consent management.", "No custom voices: Browse standard voices or add a consented custom voice."],
      ["Automations", "Flow list with run history.", "No automations: Build your first automation from a real event trigger."],
      ["Integrations", "Integration cards with connection states.", "Each card states Connected, Needs attention, Not connected, or Coming soon with the actual reason."],
      ["Analytics", "Metric pages driven only by real usage events.", "Not enough data yet: Analytics populate as your AI employees handle real conversations."],
      ["Settings", "Organization, members and roles, security, retention, billing.", "New org defaults with explicit review prompts for retention and access policies."],
    ],
  }),
  ("h2", "Onboarding Flow"),
  ("p", "Onboarding is sequenced to reach an honest first win: create an organization, create the first AI employee from a role template, add one knowledge source (or skip with the employee honestly reporting it has no business knowledge yet), choose a standard voice with a real preview, run a web chat test conversation, and only then decide whether to connect telephony or messaging. Every step shows what is real: a test chat works immediately because the chat channel is native, while a phone number is presented with its actual configuration requirements and regional availability. The flow never fabricates a demo call recording to simulate progress; it uses a clearly labeled simulated practice mode only for voice, marked Practice mode: simulated audio, so the user can hear pacing and interruption behavior without a provisioned number."),
 ],
},
{
 "num": 10, "title": "Design System, Brand and Logo Direction",
 "blocks": [
  ("h2", "Color Tokens"),
  ("table", {
    "caption": "Table 10.1: Core color tokens (RED / WHITE / BLACK system)",
    "ratios": [0.26, 0.18, 0.56],
    "headers": ["Token", "Value", "Usage rules"],
    "rows": [
      ["brand.red", "#E10600", "Primary CTAs, active states, selected navigation, waveform accents, live indicators. Intentional, never decorative fills of large areas."],
      ["brand.black.deep", "#090909", "Premium dark sections, navigation, footer, product chrome, deep contrast bands."],
      ["brand.black.soft", "#111111", "Card surfaces on dark, hover states on dark chrome."],
      ["brand.white", "#FFFFFF", "Content areas, cards on light, forms, product explanations."],
      ["brand.white.off", "#F5F5F3", "Light section backgrounds, alternating bands, table zebra on light."],
      ["brand.gray.muted", "#A1A1A1", "Secondary text, captions, inactive states on dark."],
      ["brand.gray.border", "#262626", "Borders and dividers on dark surfaces."],
      ["semantic.status", "Derived neutrals plus brand red for live/urgent; green and amber tuned to low saturation for success and warning.", "Status is never communicated by color alone; every state pairs an icon or label."],
    ],
  }),
  ("p", "The red is strategic, never atmospheric. It appears where the product is alive: a live call indicator, the waveform peak, the primary action. Black carries structure and seriousness; white carries clarity. Explicitly banned: purple and blue AI gradients, neon cyberpunk styling, glassmorphism panels, rainbow or red-on-red gradients, cartoonish AI imagery, emoji icons, generic robot illustration, floating blobs, and pill-shaped everything. Neutral hierarchy is built from the black and white axis, so the palette stays three-voiced: red speaks, black structures, white clarifies."),
  ("h2", "Typography"),
  ("p", "One display face and one interface face, both justified by function. Display: a geometric-intermediate sans with strong caps and tight tracking for headlines and the wordmark, giving the confidence of a network operator rather than a startup template. Interface: a highly readable UI sans with excellent numerals and tabular figures for dashboards, transcripts, and durations. Both are loaded as two weights each (regular, bold) plus one mono for transcripts and system events, because transcript reading benefits from a mono rhythm that visually separates machine-logged events from speech. Type scale runs from 64px display down to a 13px floor for meta text, with spacing tokens in a 4px base grid."),
  ("h2", "Logo Direction"),
  ("p", "The mark concept is a speech-act monogram: the DEYOUNG D constructed from two offset vertical bars and a horizontal voice bar, forming a letterform that reads as both a D and a leveled waveform in a single glance. It deliberately avoids the AI cliches (no brain, robot, circuit, infinity, gradient orb). The system delivers: primary lockup (monogram plus DEYOUNG COMMUNICATION wordmark, left-aligned), compact mark (monogram alone for favicon and app icon), wordmark alone for co-branding contexts, monochrome versions in pure black and pure white, light and dark variants with adjusted bar weights for equal optical mass, and a 3D-extrudable version using clean rectangular geometry with no fine detail, specified in Chapter 11's material tokens. The wordmark sets DEYOUNG in the display face with COMMUNICATION in tracked caps below, establishing the two-line hierarchy used across the site and product chrome."),
  ("h2", "Component Standards"),
  ("table", {
    "caption": "Table 10.2: Component system highlights",
    "ratios": [0.22, 0.78],
    "headers": ["System", "Standard"],
    "rows": [
      ["Buttons", "Red primary with white text; black secondary; ghost tertiary; 2px radius (sharp, not pill); loading states replace label text with real operation state; disabled requires a tooltip reason."],
      ["Forms", "White surfaces, 1px neutral borders, red only for focus and error; validation messages explain the fix; labels always visible, never placeholder-only."],
      ["Status", "Five states across the product: live (red pulse plus label), needs attention (amber plus icon), connected (green plus check), not connected (neutral), coming soon (dashed border plus label). Never color-only."],
      ["Tables", "Dense professional grid: sticky headers, zebra with off-white, mono numerals right-aligned, row actions in a fixed trailing column."],
      ["Navigation", "Dark chrome with white text; active section marked by red left rule and white text; muted gray for inactive; keyboard-accessible with visible focus."],
      ["Toasts and modals", "Toasts for operation outcomes with real success or failure; modals reserved for destructive or consent-gated actions with explicit consequences written out."],
      ["Iconography", "One professional icon set (stroke-based, 1.5px), no emoji anywhere in UI chrome."],
    ],
  }),
 ],
},
{
 "num": 11, "title": "3D and Motion System Proposal",
 "blocks": [
  ("h2", "Philosophy"),
  ("p", "3D exists to make the product's real-time, physical nature legible: a live voice conversation, a running automation, the path of a request through workers. Every animated element must map to something the product is actually doing, driven by typed data streams from real backend state. If a scene cannot be bound to real data, it does not ship. Red is the only color permitted to move with intensity; black and white stay structural and static. Motion should feel mechanical and precise, like calibrated hardware, with a single fixed key light and soft fill consistent across every scene so the brand reads as one studio setup."),
  ("h2", "Scene Plan"),
  ("table", {
    "caption": "Table 11.1: Approved 3D scenes",
    "ratios": [0.26, 0.46, 0.28],
    "headers": ["Scene", "Data binding and behavior", "Placement"],
    "rows": [
      ["Homepage hero", "Physically modeled phone plus desktop pairing showing a live call UI, built from actual product components, rendered at slight tilt with cursor parallax; no spinning, no idle loops.", "/ homepage only"],
      ["Live call waveform", "True 3D waveform mesh driven by real amplitude and frequency data of the active or most recent call; idle renders as a flat, calm baseline.", "Live Calls room, Voice Studio preview"],
      ["Voice signature", "Spectral visualization generated from an actual voice sample, used to differentiate voices at a glance.", "Voice Studio catalog"],
      ["Worker topology diagram", "Isometric system diagram of the real worker architecture, rotatable, with the option to highlight the live path of a request.", "/developers, /product pages"],
      ["Automation canvas (optional view)", "Isometric node-graph for complex automations, switchable to standard 2D flowchart.", "Automations section (Phase 2)"],
      ["Logo sting", "Sub-1-second extrusion and assembly of the wordmark for loading states; skippable, never blocking.", "App boot, brand video"],
    ],
  }),
  ("p", "Explicitly not using 3D: marketing feature grids, testimonials, pricing tables, and any element whose purpose is to look futuristic rather than explain the product. These stay flat, typographic, and fast. This restraint is a stated design rule, not a preference, and it is on the Section 35-style audit checklist for every page review."),
  ("h2", "Performance Budget and Degradation"),
  ("table", {
    "caption": "Table 11.2: Rendering tiers and budgets",
    "ratios": [0.20, 0.44, 0.36],
    "headers": ["Tier", "Definition", "Budget"],
    "rows": [
      ["Full 3D (WebGL)", "Capable desktop and modern mobile.", "60 fps target on mid-tier hardware; hero scene under 150k triangles and 40 draw calls; waveform under 60k triangles; bundle code-split and lazy-loaded."],
      ["Reduced 3D", "Mid-tier mobile; fewer particles and capped frame rate.", "30 fps floor, half the mesh budget, no post-processing."],
      ["Static and CSS fallback", "Low-end devices, prefers-reduced-motion, WebGL unavailable, first paint before 3D bundle loads.", "Same information, zero motion: CSS waveform bars with real amplitude data, SVG worker diagram, static hero composition. Page fully interactive before 3D loads."],
    ],
  }),
  ("p", "Data binding is enforced architecturally: no 3D component may own fake internal state used only to animate itself; every animated value subscribes to a typed stream (call amplitude series, worker activity events, automation run state). The idle rule is absolute: if nothing real is happening, the element is visibly still. Accessibility requires prefers-reduced-motion to disable camera movement, auto-rotation, and looping while preserving data-driven changes (the waveform still reflects real audio, without flourish), and every scene ships a text or ARIA-labeled equivalent describing what it shows. Motion tokens: mechanical easing with sharp attack and precise settle, no bounce or elastic curves; maximum idle animation is none."),
 ],
},
{
 "num": 12, "title": "Responsive and Deployment Strategy",
 "blocks": [
  ("h2", "Responsive Strategy"),
  ("table", {
    "caption": "Table 12.1: Breakpoints and layout behavior",
    "ratios": [0.20, 0.40, 0.40],
    "headers": ["Range", "Marketing site", "Application"],
    "rows": [
      ["1280px and up", "Full hero pairing, three-column feature systems, wide tables.", "Sidebar plus three-pane rooms (list, detail, context)."],
      ["1024-1279px", "Hero simplifies to phone-forward composition; two-column features.", "Collapsible sidebar; two panes with context drawer."],
      ["768-1023px", "Stacked sections; diagram switches to SVG fallback tier.", "Icon rail navigation; single pane with master-detail switching."],
      ["Under 768px", "Single column; all 3D drops to static or CSS tier; tap targets 44px.", "Bottom tab navigation on Home, Calls, AI, Inbox, More patterns; takeover flows designed mobile-first."],
    ],
  }),
  ("p", "The web app is designed so that monitoring and takeover work well on a phone, because that is what an owner actually does when an escalation alert fires at dinner. The future native app reuses these interaction patterns rather than shrinking the desktop. Mobile performance rules apply the Chapter 11 reduced budgets by default on small viewports, and every form validates inline with inputs sized to avoid OS zoom jumps."),
  ("h2", "Deployment Architecture"),
  ("p", "Phase 0 deployment keeps the entire platform on free-tier-capable infrastructure: the Next.js site and API on a serverless host with hobby-tier pricing; PostgreSQL on a free-tier managed Postgres; Redis on a free-tier serverless Redis; object storage on zero-egress S3-compatible storage; and the voice media layer on LiveKit Cloud's entry tier or a self-hosted LiveKit node when a SIP trunk demands it. Workers run as small containers on a host with scale-to-zero where the platform allows, or as scheduled functions in the serverless path. The deployment unit boundaries match the worker boundaries, so each worker can be promoted to dedicated hosting as load justifies it without code changes."),
  ("bullets", [
   "Environments: production, staging (isolated data, same provider configuration shape), and ephemeral preview deployments per branch.",
   "CI: type-check, lint, unit and integration tests, dependency audit, client-bundle secret scan, Playwright smoke suite on marketing and app shells, and Lighthouse budget gates on key pages.",
   "Database changes ship only via reviewed migrations; migrations are reversible or paired with a rollback plan.",
   "Observability from day one: structured logs, per-worker error rates, provider latency histograms, and an honest system status page that reflects real probes.",
   "Backups: daily Postgres snapshots with documented restore drills; object storage versioning on recordings and knowledge documents.",
  ]),
 ],
},
{
 "num": 13, "title": "Cost Analysis and Free-First Strategy",
 "blocks": [
  ("h2", "Provider Cost Structure"),
  ("table", {
    "caption": "Table 13.1: Variable cost components per call minute (public list rates, late 2025-2026, order of magnitude)",
    "ratios": [0.26, 0.24, 0.50],
    "headers": ["Component", "Typical range", "Notes"],
    "rows": [
      ["Streaming STT", "$0.005-0.01 / min", "Deepgram Nova-class streaming rates publicly listed around $0.0048-0.0092 per minute depending on channel and plan."],
      ["LLM (conversational)", "$0.005-0.05 / min", "Depends on model tier and prompt size; first-token speed favors mid-tier models with streaming."],
      ["Streaming TTS", "$0.01-0.10 / min", "Ranges from efficient neural voices to premium cloned voices; per-provider plan tiers swing this widely."],
      ["Telephony", "$0.005-0.03 / min", "SIP trunk termination varies by destination; Nigerian routes and messaging priced separately."],
      ["Platform margin", "Set by tier", "Zero on BYO-keys tier; usage-billed on managed tier; never charged on provider costs the customer pays directly."],
    ],
  }),
  ("p", "These figures are planning magnitudes from public pricing pages and must be re-verified before any public claim, which is why the pricing page itself will present estimates with their basis rather than false precision. The structural point stands regardless of rate drift: provider cost is the floor, and the platform's honest differentiation is decoupling its own margin from that floor."),
  ("h2", "Infrastructure Cost Tiers"),
  ("table", {
    "caption": "Table 13.2: Fixed infrastructure cost by stage",
    "ratios": [0.24, 0.34, 0.42],
    "headers": ["Stage", "Monthly fixed cost", "What it buys"],
    "rows": [
      ["Development (Phase 0)", "$0-5", "Serverless hosting free tier, free-tier Postgres and Redis, zero-egress storage, preview deployments."],
      ["First customers (Phase 1)", "$15-45", "Paid serverless tier, small always-on worker host for call reliability, LiveKit entry tier, backups."],
      ["Growth (Phase 2)", "$150-400", "Dedicated worker autoscaling, managed Postgres with read replica, multi-region SIP capacity, observability stack."],
    ],
  }),
  ("h2", "Free-First Architecture Decisions"),
  ("p", "The free-first strategy is a set of architectural commitments, not a discount: open-source core (Next.js, LiveKit, Postgres, Redis, Prisma); provider abstraction with BYO keys so an account can run entirely on its own provider spend with zero platform fee; idle shutdown so an organization with no traffic consumes no worker compute; queue-based activation so bursts degrade gracefully instead of billing for standing capacity; caching of knowledge retrieval and customer profiles to cut repeated provider calls; and usage-based activation so every metered thing is visible in the usage ledger before it bills. Tiers are honestly separated as FREE (BYO keys, all product surfaces, real limits), LOW COST (managed providers with usage billing), PAID (team features, automations at scale), and ENTERPRISE (SSO, audit export, custom retention, regional data residency options). Security and reliability are never traded to claim something is free: the free tier uses the same encryption, isolation, and audit paths as paid tiers."),
 ],
},
{
 "num": 14, "title": "Risk Register and Implementation Roadmap",
 "blocks": [
  ("h2", "Risk Register"),
  ("table", {
    "caption": "Table 14.1: Top risks with mitigations",
    "ratios": [0.26, 0.12, 0.12, 0.50],
    "headers": ["Risk", "Likelihood", "Impact", "Mitigation"],
    "rows": [
      ["Voice latency regresses beyond conversational budget", "Medium", "High", "Per-stage latency histograms in production; provider routing by latency policy; prompt sizing reviews; early-TTS onset preserved in the pipeline contract."],
      ["Telephony provisioning blocks first customers", "Medium", "High", "Twilio alternate ingress; regional number catalog with honest availability; web chat ships as the immediately working channel so onboarding never blocks on telephony."],
      ["WhatsApp per-message economics erode margins (Nigeria charging from Oct 2026)", "High", "Medium", "Per-conversation cost model surfaced in UI; SMS fallback; template and session types routed by cost policy."],
      ["AGPL contamination from reference projects", "Low", "High", "Independent implementation policy; CI license scan on dependencies; documented clean-room process for studied architectures."],
      ["Consent or recording compliance gap in a target jurisdiction", "Medium", "High", "Consent artifacts as schema-level lineage; per-jurisdiction disclosure config; audit exports; legal review checkpoint before telephony launch per market."],
      ["Provider policy or price change (STT, LLM, TTS)", "High", "Medium", "Two providers per slot behind one interface; BYO keys; usage ledger makes cost drift visible to owners immediately."],
      ["LiveKit Cloud tier limits at growth", "Medium", "Medium", "Self-hosted LiveKit as scale path; media layer isolated behind the media gateway so swap is deployment-level."],
      ["Honest-empty-state product reads as unfinished to skeptics", "Medium", "Medium", "Copy and design investment in empty states as onboarding moments; Practice mode for voice; docs that explain the honesty principle."],
      ["Abuse of outbound calling capability", "Medium", "High", "Authorized outbound only with consent and rate ceilings; abuse queue in admin; feature-flagged rollout; regional compliance gates."],
      ["Solo-founder delivery bandwidth", "High", "Medium", "Phase gates in this roadmap; P0 scope discipline; automated QA gates in CI to hold quality while velocity is limited."],
    ],
  }),
  ("h2", "Implementation Roadmap"),
  ("table", {
    "caption": "Table 14.2: Phase plan (maps to the 19-phase master process)",
    "ratios": [0.22, 0.42, 0.36],
    "headers": ["Phase", "Scope", "Exit criteria"],
    "rows": [
      ["Phase 0: Foundation (now)", "Brand system and design tokens; marketing site core pages; auth; organization and employee schema; app shell with eleven sections and honest empty states; web chat employee with real LLM behind provider abstraction; audit log and usage events live.", "A signup can create an org, build an employee, and hold a real web chat conversation with transcript persistence and audit entries."],
      ["Phase 1: Voice core", "LiveKit media path; SIP trunk inbound; streaming STT and TTS; turn detection and barge-in; live call control room with real waveform and transcript; knowledge ingestion and retrieval; SMS channel; takeover flows.", "A real phone call is answered, interrupted, escalated, and taken over by a human, with all events logged."],
      ["Phase 2: Scale product", "WhatsApp channel with consented opt-in; automations engine and canvas; voice studio with consented cloning and revocation; analytics rollups; integrations registry with encrypted BYO keys; agency multi-org features.", "Agency onboards a client end to end; automation runs from a real trigger to a logged outcome."],
      ["Phase 3: Mobile and market", "Native mobile companion (waitlist converts to TestFlight and Play tracks); regional telephony expansion; pricing page with verified cost basis; compliance pack (policy pages generated from enforced rules).", "Mobile app ships with takeover on the go; at least one paying organization per tier."],
    ],
  }),
  ("h2", "Immediate Next Steps"),
  ("p", "With this dossier approved as the planning baseline, Phase 2 begins with the foundation build: implement the design tokens and component library against Chapter 10, stand up the marketing core pages with the hero treatment from Chapter 11, then the application shell with authentication, the organization and employee schema, and the eleven-section navigation with the honest empty states specified in Chapter 9. The first vertical slice to make real is the web chat employee, because it exercises the orchestrator, provider abstraction, transcript persistence, usage events, and audit logging end to end without waiting on telephony provisioning. Each subsequent phase then follows the exit criteria above, with the quality bar of the master brief applied at every gate: the product must feel like a real communications company to an investor, an enterprise buyer, and an engineer on first look, and it must never fake the evidence."),
 ],
},
]
